### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by CSystem77** [tusharojha/you-code-compiler#1]
Hey,

I am very interested in your project but I have an error:
Error Term:
> {language: 'java', code: '',input: ''}
> error: null
> statusCode: 401
> body: {error: 'Unauthorized Request', statusCode: 401}

Error Web Browser:
http://localhost:3000/ : `Output logs = undefined `
http://localhost:5000/ : `Cannot GET /`

**Comment by tusharojha** [comment]
Hi @CSystem77,
I think you need to update the config.js file with the client id and client secret of your own account at Jdoodle website before running it.

Actually, Jdoodle provides the program compilation APIs.

It is free to sign-in and take one.

**Comment by CSystem77** [comment]
thanks
