### ISSUE TITLE
Code not compiling 

### ISSUE THREAD

**Issue by AEGON247** [tusharojha/you-code-compiler#12]
There is no output seen once the code is compiled. Even if I make errors in the code, it doesn't detect them ..... so overall, it's not working. Refer to the below attachment for further clarity.
 
![Screenshot 2021-08-08 at 10 03 11 AM](https://user-images.githubusercontent.com/80191820/128620895-c55e5829-537e-48c0-978a-9d33f8960d66.png)

**Comment by tusharojha** [comment]
@AEGON247 
Are you running this project on your local machine or this screenshot is from this website: https://you-code-compiler.herokuapp.com

**Comment by AEGON247** [comment]
> @AEGON247
> Are you running this project on your local machine or this screenshot is from this website: https://you-code-compiler.herokuapp.com

Yes I was running it on my machine. I tried on the website and it works fine. Thanks for the clarity.

**Comment by tusharojha** [comment]
By the way, to make it work on your machine you have to add the client Id & secret from JDOODLE. 
This project uses JDOODLE apis to execute programs.

check the ./config.js file in the project.
